FROM java:8-jre
LABEL maintainer="qing"
LABEL version="1.0.0"
LABEL description="hahahahha"

COPY /boot-38-1-1.jar /app/
CMD ["java", "-Xms500m", "-Xmx1024m", "-jar", "/app/boot-38-1-1.jar"]

EXPOSE 8081
